name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v2

      # 2. GCP 인증 설정
      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # 3. GCP 프로젝트 및 리전 설정
      - name: Configure Google Cloud project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}

      # 4. Docker 빌드 및 Artifact Registry에 이미지 푸시 (x86 아키텍처로 빌드)
      - name: Build and push Docker image (x86/amd64)
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/action_practice"
          gcloud builds submit --tag $IMAGE_NAME --platform=linux/amd64

      # 5. Cloud Run에 배포
      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/action_practice"
          gcloud run deploy action-practice \
            --image $IMAGE_NAME \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated